### ISSUE TITLE
About users being allowed to create personalized models

### ISSUE THREAD

**Issue by blacksmithop** [kevinthedang/discord-ollama#131]
From "Allow others to create their own models personalized for their own servers!" I understand that you want to allow users to customize their own LLMs which would normally involve fine-tuning them over a dataset. However ,I in this case I believe you're actually thinking of allowing users to configure the System Message and adding  a RAG pipeline to customize the knowledge the LLM has access to.
Both these ideas sound great, I am just not certain if the compute cost of fine-tuning a model would be worthwhile, not to mention their storage.

Check out [Unsloth](https://github.com/unslothai/unsloth) if you're interested in going down this path.

**Comment by JT2M0L3Y** [comment]
@blacksmithop you are correct, thanks for the helpful insight! 
We do intend for the "model create" to extend simply to providing addition context for models via Ollama's model file infrastructure (i.e., providing context with the system message).

However, due to the flexibility of Ollama, it is also possible to fine-tune an LLM and provide this as the base model to be used with the discord client. This does not fall directly under our goals for developing this app at this time. But, we have certainly kept this in the back of our minds...

Again, thank you for the clarification and the resource you provided. An RAG pipeline is precisely the goal! I made a rough attempt at something like this with GCP's pub/sub and cloud function tools back in March/April; but that did not come to fruition. Instead, it was pushed onto the backlog.
